name: CI-CD
on:
  push:
    branches: ["main"]
env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$TAG ./app
          docker push $IMAGE_NAME:$TAG
          sed -i "s|docker.io/.*/hello-cicd:.*|docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello-cicd:${TAG}|g" k8s/app-deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/app-deployment.yaml
          git commit -m "update image ${TAG}" || echo "no change"
          git push
