apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-cicd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gustaaavolucas/petz-desafio.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
